# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service 

apiVersion: v1 
kind: Service 

metadata: 
  name: angular-service
  namespace: visi
spec: 
  selector: 
    app: angular 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 30011 
  type: NodePort 
